
package ifneeded cmdr                   1.1 [list source [file join $dir cmdr.tcl]]
package ifneeded cmdr::actor            1.1 [list source [file join $dir actor.tcl]]
package ifneeded cmdr::config           1.1 [list source [file join $dir config.tcl]]
package ifneeded cmdr::help             1.1 [list source [file join $dir help.tcl]]
package ifneeded cmdr::help::json       1.1 [list source [file join $dir help_json.tcl]]
package ifneeded cmdr::help::sql        1.1 [list source [file join $dir help_sql.tcl]]
package ifneeded cmdr::help::tcl        1.1 [list source [file join $dir help_tcl.tcl]]
package ifneeded cmdr::officer          1.1 [list source [file join $dir officer.tcl]]
package ifneeded cmdr::parameter        1.1 [list source [file join $dir parameter.tcl]]
package ifneeded cmdr::private          1.1 [list source [file join $dir private.tcl]]
package ifneeded cmdr::util             1.1 [list source [file join $dir util.tcl]]
package ifneeded cmdr::validate         1.1 [list source [file join $dir validate.tcl]]
package ifneeded cmdr::validate::common 1.1 [list source [file join $dir vcommon.tcl]]
