[subsection Cmdr]

This project uses the Cmdr package to handle all command line processing.

[para] Please go to either the main repository at
[uri http://core.tcl.tk/akupries/cmdr]

or the backup at
[uri http://chiselapp.com/andreas_kupries/repositories/cmdr]

and follow the instructions given at these sites to create a working
installation. They are not repeated here. If there are problems with
these instructions please file a bug against the Cmdr project, and
not [vset PTITLE].

[para]
