[subsection Linenoise]

This project uses the [package linenoise] package to handle close-to-the-metal
interactive prompting

[para] Please go the main repository at
[uri http://github.com/andreas-kupries/tcl-linenoise]

and follow the instructions given at these sites to create a working
installation. They are not repeated here. If there are problems with
these instructions please file a bug against the Linenoise project,
and not [vset PTITLE].

[para]
