[subsection {Linenoise Facade}]

This project uses the [package linenoise::facade] package supplied by
the linenoise utilities for higher-level interaction, i.e. shells,
than provided by the plain [package linenoise].

[para] Please go to either the main repository at
[uri http://core.tcl.tk/akupries/linenoise-utilities]

or the backup at
[uri http://chiselapp.com/andreas_kupries/repositories/linenoise-utilities]

and follow the instructions given at these sites to create a working
installation. They are not repeated here. If there are problems with
these instructions please file a bug against the Cmdr project, and
not [vset PTITLE].

[para]
