#!/usr/bin/env tclsh
# -*- tcl -*-
apply {{self} {
    set selfdir [file dirname $self]
    if {[file exists $selfdir/kettle.tcl]} {
	# Look for a local copy first, for when we install ourselves.
	source $selfdir/kettle.tcl
    } else {
	# use the installed core.
	package require kettle
    }
    kettle::option::set @kettle $self
    kettle::Application
}} [file dirname [file normalize [info script]/__]]
