[subsection {Changes for version 1.1}]

The first official release of Kettle in just shy of 11 years.
[strong Note:] Version 1 was tagged 2013-02-07.

[para]
I am unable to list all the changes in detail.
Lots of (small(ish)) bug fixes, and some features.

[para]
Notable: export documentation to markdown, valgrind support.

[para]
I decided to tag and release version 1.1 because of the
changes to make [term kettle] work with Tcl 9.
