[subsection {Changes for version 1.1}]

The first official release of Kettle in just shy of 11 years.
[strong Note:] Version 1 was tagged 2013-02-07.

[para] Tagged and releases as version 1.1 because of the
changes to make [term kettle] work with Tcl 9.

[para] I am unable to list all the changes in detail.
Lots of (small(ish)) bug fixes, and some features.

[para] Small list of notables:

[list_begin enumerated]
[enum] Support for and work with Tcl 9.
[enum] Export documentation to markdown
[enum] Valgrind support.
[list_end]
