[comment {-*- tcl -*- --- !doctools --- manpage}]
[comment {- - -- --- ----- -------- ------------- ---------------------}]
[section {Bugs, Ideas, Feedback}]

This document, and the package it describes, will undoubtedly contain
bugs and other problems.

Please report such at the [vset kettle/track].

Please also report any ideas for enhancements you may have for either
package and/or documentation.

