[comment {--- !doctools ---}]
[comment { option :: --include-dir :: }]

[comment {- - -- --- ----- -------- ------------- ---------------------}]
[opt_def --man-dir path]

This configuration option specifies the path to the directory package
C header files will be installed into.

[para] The default value is [file [var --prefix]/include].

[comment {- - -- --- ----- -------- ------------- ---------------------}]
